services:
  database:
    image: mysql:8.0-debian
    env_file:
      - db-secret.env
    restart: always
    ports:
      - 3306:3306
    volumes:
      - cova_data:/var/lib/mysql
    networks:
      cova:
  admina:
    image: adminer
    ports:
      - 8585:8080
    depends_on:
      - database
    restart: always
    networks:
      cova:
volumes:
  cova_data:
networks:
  cova: