server:
  port: 8080

MYSQL_ROOT_PASSWORD: super_admin
MYSQL_DATABASE: tm-db
MYSQL_USER: dev_user
MYSQL_PASSWORD: cova
MYSQL_HOST: localhost

DDL_AUTO_SCHEMA: update


## JWT CONFIG PROPERTIES size min 256 bits
JWT_SECRET_HASH: ZUk0dU9Ma2gydmRLclNyVFBLMllYVVpLY1R0QXFyYXB6dGJ0SHIya3FwQw==
### TOKEN EXPIRATION TIME unit: days
JWT_EXPIRY_TIME: 7
