spring:
  application:
    name: TM-API
  config:
    import: "file:./db-secret.env[.properties],file:./app-config.yml[.properties]"
  profiles:
    active: ${ACTIVE_ENV}
    ### DATABASE CONFIG PROPERTIES.
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_SCHEMA}
    database-platform:
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

