server:
  port: 8000

spring:
  application:
    name: TM-API
  profiles:
    active: ${ACTIVE_ENV:dev}

    ### DATABASE CONFIG PROPERTIES.
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_SCHEMA:update}
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:tm-db}
    username: ${MYSQL_USER:dev_user}
    password: ${MYSQL_PASSWORD:cova}

